-- 002_campaigns_seed.sql
-- Demo data: the 12 campaigns (OBSERVATIONS) from src/data/mockData.js, same ids.
-- Run in the Supabase SQL Editor AFTER migrations/002_campaigns.sql
-- and BEFORE migrations/003_measurements_campaign_fk.sql.
-- Safe to re-run: existing ids are skipped (rows are not overwritten).
-- Generated from mockData.js; sort_order keeps the original display order.

insert into public.campaigns
  (id, slug, metric, icon, title_he, title_en, title_ru, desc_he, desc_en, desc_ru,
   status, region, difficulty, equipment, protocol_url, center_lat, center_lng, zoom, sort_order)
values
  ('obs-schoolyard-heat',
   'schoolyard-heat',
   'temperature',
   'Thermometer',
   'חום בחצר בית הספר',
   'Schoolyard heat',
   'Жара на школьном дворе',
   'מיפוי הבדלי טמפרטורה בין פינות מוצללות לחשופות בחצר.',
   'Mapping temperature gaps between shaded and exposed corners of the yard.',
   'Картирование разницы температур между тенистыми и открытыми углами двора.',
   'collecting',
   'center',
   'easy',
   array['תרמומטר דיגיטלי', 'טלפון עם GPS']::text[],
   '#/protocol/schoolyard-heat',
   32.09,
   34.85,
   8,
   1),
  ('obs-urban-heat-island',
   'urban-heat-island',
   'temperature',
   'Building2',
   'איי חום עירוניים',
   'Urban heat islands',
   'Городские острова тепла',
   'השוואת טמפרטורה בין מרכזי ערים לשכונות ירוקות בשעות אחר הצהריים.',
   'Comparing afternoon temperature between city centres and green neighbourhoods.',
   'Сравнение дневной температуры между центром города и зелёными районами.',
   'collecting',
   'center',
   'medium',
   array['תרמומטר דיגיטלי', 'מדחום אינפרא-אדום', 'טלפון עם GPS']::text[],
   '#/protocol/urban-heat-island',
   32.1,
   34.83,
   8,
   2),
  ('obs-asphalt-vs-grass',
   'asphalt-vs-grass',
   'temperature',
   'SunMedium',
   'אספלט מול דשא',
   'Asphalt vs grass',
   'Асфальт против травы',
   'מדידת טמפרטורת פני שטח על אספלט, בטון ודשא באותה שעה.',
   'Surface temperature over asphalt, concrete and grass at the same hour.',
   'Температура поверхности асфальта, бетона и травы в один и тот же час.',
   'collecting',
   'lowlands',
   'easy',
   array['מדחום אינפרא-אדום']::text[],
   '#/protocol/asphalt-vs-grass',
   31.9,
   34.8,
   9,
   3),
  ('obs-morning-baseline',
   'morning-baseline',
   'temperature',
   'Sunrise',
   'קו בסיס — טמפרטורת בוקר',
   'Morning temperature baseline',
   'Базовая утренняя температура',
   'סדרת מדידות ב-07:00 לאורך האביב לבניית קו בסיס אזורי.',
   'A 07:00 series through spring to build a regional baseline.',
   'Серия измерений в 07:00 всю весну для региональной базовой линии.',
   'completed',
   'north',
   'easy',
   array['תרמומטר דיגיטלי']::text[],
   '#/protocol/morning-baseline',
   32.8,
   35.1,
   9,
   4),
  ('obs-humidity-from-air',
   'humidity-from-air',
   'humidity',
   'Droplets',
   'לחות מהאוויר',
   'Humidity from air',
   'Влага из воздуха',
   'חישוב לחות אבסולוטית מטמפרטורה ולחות יחסית, ומיפוי מפרץ מול פנים הארץ.',
   'Absolute humidity from temperature and RH, coast vs inland.',
   'Абсолютная влажность из температуры и ОВ, побережье против внутренних районов.',
   'collecting',
   'haifa',
   'medium',
   array['מד לחות (היגרומטר)', 'תרמומטר דיגיטלי']::text[],
   '#/protocol/humidity-from-air',
   32.5,
   34.95,
   8,
   5),
  ('obs-galilee-humidity',
   'galilee-humidity',
   'humidity',
   'CloudDrizzle',
   'לחות בגליל',
   'Galilee humidity',
   'Влажность в Галилее',
   'מדידות לחות בעמקים ובפסגות הגליל בעונת המעבר.',
   'Humidity in Galilee valleys and ridgelines during the transition season.',
   'Влажность в долинах и на хребтах Галилеи в межсезонье.',
   'completed',
   'north',
   'medium',
   array['מד לחות (היגרומטר)']::text[],
   '#/protocol/galilee-humidity',
   32.95,
   35.3,
   9,
   6),
  ('obs-dark-skies',
   'dark-skies',
   'skyBrightness',
   'Moon',
   'שמיים כהים',
   'Dark skies',
   'Тёмное небо',
   'מדידת בהירות שמיים בלילה עם חיישן SQM כדי למפות זיהום אור.',
   'Night sky brightness with an SQM sensor to map light pollution.',
   'Яркость ночного неба датчиком SQM для картирования светового загрязнения.',
   'collecting',
   'center',
   'hard',
   array['חיישן SQM', 'טלפון עם GPS', 'שעון']::text[],
   '#/protocol/dark-skies',
   32,
   34.9,
   8,
   7),
  ('obs-negev-sky',
   'negev-sky',
   'skyBrightness',
   'Stars',
   'בהירות שמיים בנגב',
   'Negev sky brightness',
   'Яркость неба в Негеве',
   'סדרת מדידות מהמצפה ומהיישובים סביב מכתש רמון.',
   'A series from the observatory and towns around Makhtesh Ramon.',
   'Серия от обсерватории и посёлков вокруг кратера Рамон.',
   'collecting',
   'south',
   'hard',
   array['חיישן SQM']::text[],
   '#/protocol/negev-sky',
   30.7,
   34.8,
   8,
   8),
  ('obs-light-pollution-census',
   'light-pollution-census',
   'skyBrightness',
   'Lightbulb',
   'מפקד זיהום אור',
   'Light pollution census',
   'Перепись светового загрязнения',
   'מדידה חד-פעמית מתואמת מכל בתי הספר באותו לילה ללא ירח.',
   'A single coordinated reading from every school on the same moonless night.',
   'Одно согласованное измерение от каждой школы в одну безлунную ночь.',
   'completed',
   'center',
   'medium',
   array['חיישן SQM']::text[],
   '#/protocol/light-pollution-census',
   32.2,
   34.9,
   8,
   9),
  ('obs-roadside-air',
   'roadside-air',
   'airQuality',
   'Wind',
   'זיהום אוויר ליד כבישים',
   'Roadside air quality',
   'Качество воздуха у дорог',
   'מדידת PM2.5 במרחקים שונים מציר תנועה ראשי בשעת עומס.',
   'PM2.5 at increasing distance from a main traffic artery at rush hour.',
   'PM2.5 на разном удалении от главной магистрали в час пик.',
   'collecting',
   'center',
   'medium',
   array['מד חלקיקים ניד (PM2.5)', 'טלפון עם GPS']::text[],
   '#/protocol/roadside-air',
   32.07,
   34.8,
   9,
   10),
  ('obs-desert-dust',
   'desert-dust',
   'airQuality',
   'CloudFog',
   'אבק מדברי',
   'Desert dust',
   'Пустынная пыль',
   'מעקב אחר אירועי אבק בנגב ובשפלה לפי ריכוזי חלקיקים.',
   'Tracking dust events across the Negev and lowlands by particle load.',
   'Отслеживание пыльных явлений в Негеве и низменности по концентрации частиц.',
   'collecting',
   'south',
   'easy',
   array['מד חלקיקים ניד (PM2.5)']::text[],
   '#/protocol/desert-dust',
   31.3,
   34.7,
   8,
   11),
  ('obs-winter-air',
   'winter-air',
   'airQuality',
   'Snowflake',
   'איכות אוויר בחורף',
   'Winter air quality',
   'Качество воздуха зимой',
   'מדידות ערב בשכונות מגורים בעונת ההסקה בעצים.',
   'Evening readings in residential neighbourhoods during the wood-heating season.',
   'Вечерние измерения в жилых районах в сезон печного отопления.',
   'completed',
   'jerusalem',
   'medium',
   array['מד חלקיקים ניד (PM2.5)']::text[],
   '#/protocol/winter-air',
   31.78,
   35.2,
   9,
   12)
on conflict (id) do nothing;
