import {
  Thermometer,
  Building2,
  SunMedium,
  Sunrise,
  Droplets,
  CloudDrizzle,
  Moon,
  Sparkles,
  Lightbulb,
  Wind,
  CloudFog,
  Snowflake,
  CloudRain,
  Waves,
  Leaf,
  TreePine,
  Flower2,
  Sprout,
  Bird,
  Bug,
  Fish,
  Mountain,
  Volume2,
  FlaskConical,
  Microscope,
  Gauge,
  Activity,
} from 'lucide-react';

/** Lab icons by name (campaigns.icon). The editor offers these (src/lib/labs.js → LAB_ICONS). */
const MAP = {
  Thermometer,
  Building2,
  SunMedium,
  Sunrise,
  Droplets,
  CloudDrizzle,
  Moon,
  Stars: Sparkles,
  Lightbulb,
  Wind,
  CloudFog,
  Snowflake,
  CloudRain,
  Waves,
  Leaf,
  TreePine,
  Flower2,
  Sprout,
  Bird,
  Bug,
  Fish,
  Mountain,
  Volume2,
  FlaskConical,
  Microscope,
  Gauge,
  Activity,
};

export default function ObsIcon({ name, className = 'h-5 w-5', strokeWidth = 1.75 }) {
  const Cmp = MAP[name] || Activity;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
